app_auth/urls.py
from django.urls import path
from app_auth import views

app_name="app_auth"

urlpatterns = [
    path("",views.index_view,name="index_view_name"),
    path("register/",views.register_view,name="register_view_name"),
    path("login/",views.login_view,name="login_view_name"),
    path("logout/",views.logout_view,name="logout_view_name"),
    path("change-password/",views.change_password_view,name="change_password_view_name"),

    # path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
    #     views.activate_view, name='activate_view_name'),

    path('activate-user/<uidb64>/<token>',views.activate_view, name='activate_view_name'),  
]

project_base_2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_auth.urls")),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'modern_normalize.css' %}">
    <link rel="stylesheet" href="{% static 'app_auth/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap" rel="stylesheet">
</head>

<body>


    <div>
        {% include "navbar.html" %}

        {% block content %}{% endblock content %}

    </div>

</body>

</html>

templates/navbar.html
<ul>
    <li><a href="/">Home</a></li>
    {% if user.is_authenticated %}
    <li style="text-align:center;">
        <span>Hello {{ user.username }}</span>
    </li>
    {% endif %}
    {% if user.is_authenticated %}
    <li class="right">
        <a href=" {% url 'app_auth:change_password_view_name' %} ">Change Password</a>
    </li>
    <li class="right">
        <a href=" {% url 'app_auth:logout_view_name' %} ">Logout</a>
    </li>
    {% comment %} <li>
        <a href=" {% url 'password_change' %}">Password Change</a>
    </li> {% endcomment %}
    {% else %}
    <li class="right">
        <a href=" {% url 'app_auth:register_view_name' %}">Register</a>
    </li>
    <li class="right">
        <a href=" {% url 'app_auth:login_view_name' %} ">Login</a>
    </li>
    {% endif %}
</ul>